default_install_hook_types: [commit-msg, pre-commit]
fail_fast: false
repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8 --max-line-length=120 --ignore=E203,W503 .
        language: system
        types: [python]

      - id: black
        name: black
        entry: black .
        language: system
        types: [python]

      - id: mypy
        name: mypy
        entry: mypy my_app
        language: system
        types: [python]

      - id: pytest
        name: pytest
        entry: pytest .
        language: system
        types: [python]
      - id: coverage
        name: coverage report
        entry: coverage run
        language: system
        types: [python]

      - id: bandit
        name: bandit
        entry: bandit -r .
        language: system
        types: [python]

      - id: isort
        name: isort
        entry: isort --check-only --diff .
        language: system
        types: [python]

      - id: pylint
        name: pylint
        entry: pylint .
        language: system
        types: [python]

      - id: radon-cc
        name: radon-cc
        entry: radon cc .
        language: system
        types: [python]


  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v8.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: [
          "@commitlint/config-conventional",
          "@ngx-devs/commitlint-plugin-imperative"
        ]

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.17.0
    hooks:
      - id: yamllint
        files: ".github"  # TODO: Enable for all .yaml, .yml files in repo

  # - repo: https://github.com/sqlfluff/sqlfluff
  #   rev: 1.3.0
  #   hooks:
  #     - id: sqlfluff-lint
  #       args: [--disable_progress_bar]  # progress bar pollutes GH actions
  #       files: SQL